[package]
authors.workspace    = true
categories.workspace = true
edition.workspace    = true
keywords.workspace   = true
license.workspace    = true
repository.workspace = true

description = "Library to handle syndication spec"
name        = "synd-feed"
readme      = "README.md"
version     = "0.1.3"

[dependencies]
anyhow       = { workspace = true }
async-trait  = { workspace = true }
chrono       = { workspace = true }
feed-rs      = { workspace = true }
futures-util = { workspace = true }
moka         = { workspace = true, features = ["future"] }
reqwest      = { workspace = true, features = ["stream"] }
serde_json   = { workspace = true }
thiserror    = { workspace = true }
tokio        = { workspace = true }
tracing      = { workspace = true }

[lints]
workspace = true
