[package]
authors.workspace    = true
categories.workspace = true
description          = "Library to handle syndication spec"
edition.workspace    = true
license.workspace    = true
name                 = "synd_feed"
repository.workspace = true
version              = "0.1.0"

[dependencies]
anyhow       = { workspace = true }
async-trait  = { workspace = true }
chrono       = { workspace = true }
feed-rs      = { workspace = true }
futures-util = { workspace = true }
moka         = { workspace = true, features = ["future"] }
reqwest      = { workspace = true, features = ["stream"] }
thiserror    = "1.0.56"
tokio        = { workspace = true }
tracing      = { workspace = true }
