version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "07:00"
      timezone: "Asia/Tokyo"
    labels: ["dependencies/github_actions"]
  - package-ecosystem: cargo
    directory: /
    schedule: # github does not support yaml anchors
      interval: weekly
      time: "07:00"
      timezone: "Asia/Tokyo"
    labels: ["dependencies/rust"]
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
    # If a dependency doesn't belong to any group, Dependabot will continue to raise single pull requests to update the dependency to its latest version as normal.
    groups:
      opentelemetry:
        applies-to: version-updates
        patterns: ["opentelemetry*"]
      axum:
        applies-to: version-updates
        patterns: ["axum", "axum-server", "async-graphql", "async-graphq-axum"]
      rust-patch:
        applies-to: version-updates
        update-types: ["patch"]
