[workspace]
resolver = "2"
members = ["synd", "syndapi", "syndterm"]

[workspace.package]
edition = "2021"
authors = ["ymgyt"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
async-trait = { version = "0.1.77" }
anyhow = { version = "1" }
clap = { version = "4.4" }
chrono = { version = "0.4.31" }
feed-rs = { version = "1.4" }
futures-util = { version = "0.3.30" }
graphql_client = { version = "0.13.0", default-features = false }
moka = { version = "0.12.4", features = ["future"] }
reqwest = { version = "0.11.23", default-features = false, features = [
  "rustls-tls",
  "json",
] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1.35" }
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18", features = [
  "smallvec",
  "fmt",
  "ansi",
  "std",
  "env-filter",
  "time",
], default-features = false }
url = { version = "2.5.0" }
