## Programming Languages
[categories.rust]
icon = { symbol = "", color = { rgb = 0xF74C00 } } # nf-linux-ferris

[categories.go]
aliases = ["golang"]
icon    = { symbol = "", color = { name = "cyan" } } # nf-custom-go

[categories.c]
icon = { symbol = "󰙱" } # nf-custom-go

[categories.cpp]
aliases = ["cplus"]
icon    = { symbol = "" }

[categories.haskell]
icon = { symbol = "󰲒" } # nf-md-language_haskell

[categories.java]
icon = { symbol = "󰬷" } # nf-md-language_java

[categories.javascript]
aliases = ["js"]
icon    = { symbol = "" } # nf-dev-javascript

[categories.typescript]
aliases = ["ts"]
icon    = { symbol = "" }

[categories.kotlin]
icon = { symbol = "󱈙" } # nf-md-language_kotlin

[categories.swift]
icon = { symbol = "󰛥" } # nf-md-language_swift

[categories.php]
icon = { symbol = "󰌟" } # nf-md-language_php

[categories.python]
icon = { symbol = "󰌠" } # nf-md-language_python

[categories.ruby]
icon = { symbol = "󰴭" } # nf-md-language_ruty

[categories.database]
aliases = ["db", "rds"]
icon    = { symbol = "\ue706" } # nf-dev-database 

[categories.sre]
icon = { symbol = "󱋌" } # nf-md-cloud_check_outline

## Cloud
[categories.cloud]
aliases = ["cncf", "cloudnative"]
icon    = { symbol = "" }        # nf-fa-cloud

[categories.aws]
icon = { symbol = "󰸏" } # nf-md-aws

[categories.gcp]
aliases = ["googlecloud"]
icon    = { symbol = "󱇶" } #nf-md-google_cloud

[categories.azure]
icon = { symbol = "" } #nf-cod-azure

[categories.kubernetes]
aliases = ["k8s"]
icon    = { symbol = "󱃾", color = { name = "blue" } } # nf-md-kubernetes

[categories.opentelemetry]
aliases = ["otel", "observability", "o11y"]
icon    = { symbol = "󰭎", color = { name = "white" } } # nf-md-telescope

## Linux
[categories.linux]
icon = { symbol = "" } #nf-fa-linux

[categories.nix]
aliases = ["nixos"]
icon    = { symbol = "", color = { name = "cyan" } } # nf-linux-nixos

[categories.ebpf]
aliases = ["bpf"]
icon    = { symbol = "󰾡", color = { name = "yello" } }

## Editor
[categories.helix]
icon = { symbol = "󰚄", color = { name = "magenta" } } # nf-md-dna

## Shell
[categories.nu]
aliases = ["nushell"]
icon    = { symbol = "" }

## Misc

[categories.book]
aliases = ["oreilly"]
icon    = { symbol = "" } # nf-fa-book

[categories.misc]
aliases = ["etc"]
icon    = { symbol = "" } # nf-cod-symbol_misc

[categories.default]
icon = { symbol = "󰎞", color = { name = "gray" } } # nf-md-note_text
