# https://docs.codecov.com/docs/codecovyml-reference
coverage:
  round: down
  range: 50..80
  status: # https://docs.codecov.com/docs/commit-status
    project:
      default:
        target: auto # use the coverage from the base commit 
        threshold: 3% # allow the coverage to drop by
    patch:
      default:
        target: 50%
ignore:
  # There are only 3 lines, but 340 lines are displayed as tracked lines, and We can't deal with it
  # https://app.codecov.io/github/ymgyt/syndicationd/blob/main/crates%2Fsynd_api%2Fsrc%2Fserve%2Flayer%2Fmod.rs
  - "crates/synd_api/src/serve/layer/mod.rs"
  - "crates/ebpf"
comment: # https://docs.codecov.com/docs/pull-request-comments
  # reach is not documented, but validator doesn't complain
  layout: "condensed_header,reach,diff,condensed_files,condensed_footer"
  hide_project_coverage: false
  require_changes: true
