[files]
extend-exclude = [
  # Could not fix github api typo
  "crates/synd_api/src/client/github/schema.json",
  # Ignore commit message typo
  "CHANGELOG.md",
]

[default.extend-words]
"ratatui" = "ratatui"
