[advisories]
ignore = [
  # yaml-rust unmaintained, but serde_yaml use it
  "RUSTSEC-2024-0320",
]

[yanked]
# in derivations we could not connect net
# crate-audit> error: couldn't check if the package is yanked: not found: No such crate in crates.io index: foo
enabled      = false
update_index = false
