[advisories]
ignore = [
  # yaml-rust unmaintained, but serde_yaml use it
  "RUSTSEC-2024-0320",
  # parse_duration
  # Denial of service through parsing payloads with too big exponent
  # No fixed upgrade available
  "RUSTSEC-2021-0041",
]
