receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
processors:
  resource/loki:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: service.namespace,service.name,service.version
      - action: insert
        key: loki.format
        value: logfmt # logfmt | json   raw
exporters:
  loki:
    endpoint: ${env:LOKI_ENDPOINT}
    default_labels_enabled:
      exporter: false
      job: false
      instance: false
      level: false
  debug:
    verbosity: detailed
service:
  pipelines:
    # logs:
    #   receivers: [otlp]
    #   processors: [resource/loki]
    #   exporters: [debug]
    metrics:
      receivers: [otlp]
      exporters: [debug]
