[package]
authors.workspace     = true
categories.workspace  = true
description.workspace = true
edition.workspace     = true
license.workspace     = true
name                  = "synd_test"
readme.workspace      = true
repository.workspace  = true
version               = "0.1.0"

[dependencies]
anyhow    = { workspace = true }
axum      = { workspace = true }
synd_term = { path = "../synd_term" }
tokio     = { workspace = true, features = ["rt-multi-thread", "net"] }
