[package]
authors.workspace     = true
categories.workspace  = true
description.workspace = true
edition.workspace     = true
keywords.workspace    = true
license.workspace     = true
readme.workspace      = true
repository.workspace  = true

name    = "synd-term"
version = "0.1.1"

[[bin]]
name = "synd"
path = "src/main.rs"

[dependencies]
synd-auth = { path = "../synd_auth", version = "0.1.2" }
synd-feed = { path = "../synd_feed", version = "0.1.1" }
synd-o11y = { path = "../synd_o11y", version = "0.1.1" }

anyhow         = { workspace = true }
chrono         = { workspace = true }
clap           = { workspace = true, features = ["derive", "string", "color", "suggestions", "wrap_help"] }
crossterm      = { version = "0.27.0", features = ["event-stream"] }
directories    = "5.0.1"
edit           = "0.1.5"
futures-util   = "0.3.30"
graphql_client = { workspace = true }
html2text      = { version = "0.12" }
open           = "5.0.1"
# ratatui              = { git = "https://github.com/ratatui-org/ratatui.git", branch = "main" }
ratatui              = { version = "0.26.0" }
reqwest              = { workspace = true }
serde                = { workspace = true, features = ["derive"] }
serde_json           = "1.0.111"
tokio                = { workspace = true, features = ["macros", "rt-multi-thread", "sync", "time"] }
tracing              = { workspace = true }
tracing-appender     = "0.2.3"
tracing-subscriber   = { workspace = true }
unicode-segmentation = "1.10.1"
url                  = { workspace = true }
# https://github.com/arkbig/throbber-widgets-tui/pull/5
# throbber-widgets-tui = "0.3.0"

[features]
# Integration test
integration = []

[dev-dependencies]
synd-api  = { path = "../synd_api" }
synd-test = { path = "../synd_test" }

axum-server  = { workspace = true }
kvsd         = { workspace = true }
serial_test  = { version = "3.0.0", default_features = false, features = ["async", "file_locks"] }
tempdir      = "0.3.7"
tokio-stream = "0.1.14"

[lints]
workspace = true
