name: Publish docker image
on:
  workflow_dispatch:
jobs:
  publish-synd-api-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v15
        with:
          name: syndicationd
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          nix build .#synd-api-image --accept-flake-config
          docker load --input result
          docker tag synd-api:latest ghcr.io/ymgyt/synd-api:latest
          docker image push ghcr.io/ymgyt/synd-api:latest
